### ISSUE TITLE
ci: sync is failing

### ISSUE THREAD

**Issue by isabelroses** [auxolotl/nixpkgs#13]
### Describe the bug
The CI is failing to update

### Steps To Reproduce
run workflow

### Expected behavior
CI updates successfully

### Screenshots
![image](https://github.com/auxolotl/nixpkgs/assets/71222764/bd68e083-b1de-44e1-98f0-96722e8ac5cb)

### Additional context
[logs](https://github.com/auxolotl/nixpkgs/actions/runs/8945472339/job/24574506356)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by isabelroses** [comment]
I believe the fix is changing the command to `git remote add fork url`

**Comment by isabelroses** [comment]
New issue [log](https://github.com/auxolotl/nixpkgs/actions/runs/8945631381/job/24574910978#step:6:10)

![image](https://github.com/auxolotl/nixpkgs/assets/71222764/a71a8e35-bcf8-4454-9c0a-19045c6f844a)

My git fu is not great enough to solve this one.

**Comment by Austreelis** [comment]
I couldn't verify (it's 00:51 here) but I think that if you add a remote that has commits (nixpkgs certainly does ._.) on a repo that also has commits (this fork), you can't merge them together because git can't know if the diffs have anything to deal with each other (e.g. you could add curl's git as a remote on a local nixpkgs clone and naively try to merge two branches from them). Even if they actually come from the same root, or maybe even if they're exact but-to-bit dupplicates (idk).

There's a `--allow-unrelated-history` flag for `git merge` and `rebase` iirc, but I don't remember when it's safe to use.

**Comment by isabelroses** [comment]
So after a bit of discussion with some other contributors, the solution we went for was force pushing to master our changes and to clean the reflog. Hopefully, next time the CI runs we shall know if it works.

**Comment by isabelroses** [comment]
> So after a bit of discussion with some other contributors, the solution we went for was force pushing to master with our changes. This would clean the reflog and hopefully next time the CI runs we shall know if it works.

Seem the issue still persists [log](https://github.com/auxolotl/nixpkgs/actions/runs/8946669219/job/24577627532#step:6:10)

**Comment by isabelroses** [comment]
I have a crazy idea. I think `actions/checkout@4` is the reason the action is failing because it fetches with a depth of 1 by default.

**Comment by msfjarvis** [comment]
You're on the money, checkout does default to not fetching the history because it's slow and often unnecessary for typical CI jobs. Adding `fetch-depth: 0` will force it to fetch the full history and should fix the sync job.
